name: real_image

image_shape: [3, 240, 320]
dataset_path: data/pine_demos/stack_2cups

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    right_camera:
      shape: ${task.image_shape}
      type: rgb
    # depth_camera:
    #   shape: ${task.image_shape}
    #   type: rgb
    left_camera:
      shape: ${task.image_shape}
      type: rgb
    end_effector_pose_right_arm:
      shape: [7]
      type: low_dim
  action: 
    shape: [7]

env_runner:
  _target_: diffusion_policy.env_runner.real_pine_image_runner.RealPineImageRunner

dataset:
  _target_: diffusion_policy.dataset.real_pine_image_dataset.RealPineImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False

